profiles: DEV
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.dialect.storage_engine: innodb
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/locker?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: locker
    password: locker
    druid:
      initial-size: 5
      minimum-idle: 5
      maximum-pool-size: 10
      filter:
        stat:
          enabled: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 5
    host: localhost
    port: 32768
    timeout: 3000
    jedis:
      pool:
        max-idle: 50
        min-idle: 8
        max-active: 100
        max-wait: 50

#token拦截器是否启动
interceptor:
  token: true


